### ISSUE TITLE
Introduction example error

### ISSUE THREAD

**Issue by TK-21st** [chungheng/pycodegen#2]
Tried running `introduction.ipynb` in `neural` with the latest `pycodegen`, got this error:

<img width="1082" alt="screen shot 2018-06-09 at 3 24 22 pm" src="https://user-images.githubusercontent.com/26802334/41195341-3d09fc54-6bf9-11e8-96e6-14b7a1f2b495.png">

### EDIT
The error above is encountered only for `HodgkinHuxley()` not for `Alpha()`

**Comment by chungheng** [comment]
This is an issue with neural. Fixed in the commit aa21f4c27e08e00bc8b259837516a6b084dc8c1f.
